### ISSUE TITLE
Definir as APIs a serem utilizadas

### ISSUE THREAD

**Issue by Kaoticz** [Kaoticz/Nekollector#11]
Sugiram abaixo as APIs que devemos utilizar no projeto, com links para documentação e endpoints de interesse.

**Comment by GalakCV** [comment]
Uma API boa é a do Pexels.

**https://www.pexels.com/api/documentation/**

Retorna vídeos e imagens de forma aleatória, igual a API das gata humana que o Matheus colocou. Para o trabalho podemos filtrar a API com imagens de naturezas, por exemplo.
Exemplo de endpoint que está na documentação:

**https://api.pexels.com/v1/search?query=nature&per_page=1**

Não é necessário outras APIS para funcionar, com um request HTTP e manipulação no JSON já obtemos o conteúdo. É necessário, obviamente, apenas a chave da API, é gratuito e tem um limite de request, que só para fazer o trabalho, ta ótimo.

**Comment by Kaoticz** [comment]
Não podemos usar essa API por uma questão de licença. Segundo a documentação deles:

> You may not copy or replicate core functionality of Pexels **(including making Pexels content available as a wallpaper app)**.

Precisamos de uma API que não imponha tal restrição, visto que estamos desenvolvendo um aplicativo de wallpaper.

**Comment by GalakCV** [comment]
Conferi aqui, tem outras APIS aqui que aparentemente não tem esse problema.
Uma outra alternativa é o Lorem Picsum.

Link para documentação: **https://picsum.photos/**
Endpoint de exemplo: **https://picsum.photos/id/237/200/300**

Outra alternativa, bem legal também, é a API da Nasa, nada muito complexo.
Essa API retorna fotos e vídeos do espaço, planetas, constelações, galáxias etc.

Link para documentação: **https://api.nasa.gov/** 

E a última opção é a Unsplash API, que retorna imagens aleatórias com base no filtro.
Ela tem outras funcionalidades mas o que interessa mesmo é o PHOTOS.

Link para documentação: **https://unsplash.com/documentation#search-photos**

Exemplo de Endpoint: **https://api.unsplash.com/search/photos?page=1&query=office**

**Comment by Kaoticz** [comment]
Esse link da NASA é na verdade uma lista de várias APIs diferentes. Qual delas devemos usar?

**Comment by GalakCV** [comment]
@Kaoticz 
Poderiamos utilizar a APOD, que retorna alguma imagem do universo.
Porém, li na documentação, no github, que vai precisar instalar outras coisas, não queria algo que complicasse ainda mais, seria melhor uma API que é só fazer um request e pronto, procede com essa ou vai mudar ?

**Comment by Kaoticz** [comment]
Parece bom pra mim.
